window.AUTO_STOCK_DATA = {
  "generatedAt": "2026-06-28T06:01:41.061Z",
  "source": "data/stock-master.csv",
  "priceSource": "data/price-updates.csv",
  "disclosureSource": "data/disclosures.csv",
  "edinetSource": "data/edinet-facts.csv",
  "watchlistSource": "data/watchlist.csv",
  "fetchedAt": "2026-06-28T06:01:41.032Z",
  "priceFetchedAt": "2026-06-28T06:01:41.039Z",
  "disclosureFetchedAt": "2026-06-28T06:01:41.040Z",
  "edinetFetchedAt": "2026-06-28T06:01:41.041Z",
  "nextSources": [
    "price-api",
    "edinet-api",
    "tdnet"
  ],
  "priceUpdates": 35,
  "disclosureUpdates": 5,
  "edinetUpdates": 20,
  "watchlistUpdates": 3,
  "backtestUpdates": 35,
  "autoPromotionUpdates": 0,
  "providerStatuses": [
    {
      "label": "銘柄マスタ",
      "ok": true,
      "message": "取得成功",
      "source": "data/stock-master.csv"
    },
    {
      "label": "株価",
      "ok": true,
      "message": "取得成功",
      "source": "data/price-updates.csv"
    },
    {
      "label": "適時開示",
      "ok": true,
      "message": "取得成功",
      "source": "data/disclosures.csv"
    },
    {
      "label": "EDINET相当",
      "ok": true,
      "message": "取得成功",
      "source": "data/edinet-facts.csv"
    },
    {
      "label": "監視リスト",
      "ok": true,
      "message": "取得成功",
      "source": "data/watchlist.csv"
    }
  ],
  "stocks": [
    {
      "code": "8841",
      "name": "テーオーシー",
      "sector": "不動産",
      "price": 972,
      "shares": 88217703,
      "treasuryShares": 0,
      "cash": 8500,
      "securities": 4300,
      "investmentSecurities": 18200,
      "interestDebt": 7000,
      "netAssets": 101000,
      "rentalBook": 58000,
      "rentalMarket": 186000,
      "bps": 1145,
      "eps": 44,
      "pbrLow": 0.5,
      "pbrAvg": 0.7,
      "pbrHigh": 0.95,
      "perLow": 12,
      "perAvg": 16,
      "perHigh": 22,
      "dataConfidence": "確認済み",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自社株買い",
      "history": [
        610,
        650,
        620,
        690,
        720,
        760,
        800,
        836,
        972
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/8841"
      },
      "priceAsOf": "2026-06-26",
      "disclosures": [
        {
          "code": "8841",
          "publishedAt": "2026-06-18",
          "title": "自己株式取得に係る事項の決定に関するお知らせ",
          "url": "https://example.com/8841-buyback",
          "catalysts": [
            {
              "type": "自社株買い",
              "score": 8
            }
          ]
        }
      ],
      "watchlist": {
        "status": "監視",
        "note": "不動産含み益と資本政策の進捗を見る"
      },
      "backtest": {
        "code": "8841",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (504円以下)",
        "sellTiming": "目標の90%付近 (971円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "6505",
      "name": "東洋電機製造",
      "sector": "電機",
      "price": 1955,
      "shares": 9735500,
      "treasuryShares": 420000,
      "cash": 8300,
      "securities": 620,
      "investmentSecurities": 9900,
      "interestDebt": 3100,
      "netAssets": 32300,
      "rentalBook": 2100,
      "rentalMarket": 4800,
      "bps": 3430,
      "eps": 101,
      "pbrLow": 0.32,
      "pbrAvg": 0.52,
      "pbrHigh": 0.78,
      "perLow": 10,
      "perAvg": 18,
      "perHigh": 24,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": true,
      "risk": "",
      "catalyst": "中期経営計画 / PBR改善",
      "history": [
        880,
        930,
        900,
        1010,
        1080,
        1120,
        1160,
        1180,
        1955
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/6505"
      },
      "priceAsOf": "2026-06-26",
      "disclosures": [
        {
          "code": "6505",
          "publishedAt": "2026-06-18",
          "title": "中期経営計画の進捗および資本コストを意識した経営の実現に向けた対応について",
          "url": "https://example.com/6505-midterm",
          "catalysts": [
            {
              "type": "中期経営計画",
              "score": 5
            },
            {
              "type": "PBR改善",
              "score": 6
            }
          ]
        }
      ],
      "watchlist": null,
      "backtest": {
        "code": "6505",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (960円以下)",
        "sellTiming": "目標の90%付近 (2,387円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 1,
        "winRate": 100,
        "averageReturn": 110.2,
        "maxDrawdown": -3.2,
        "bestScore": 172.7,
        "financialScreeningStatus": "慎重確認",
        "financialScreeningCautions": "ネット有利子負債が重い -47.59% / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "3123",
      "name": "サイボー",
      "sector": "繊維・不動産",
      "price": 605,
      "shares": 12891200,
      "treasuryShares": 0,
      "cash": 2550,
      "securities": 300,
      "investmentSecurities": 4300,
      "interestDebt": 2200,
      "netAssets": 13400,
      "rentalBook": 24700,
      "rentalMarket": 41400,
      "bps": 1040,
      "eps": 30,
      "pbrLow": 0.55,
      "pbrAvg": 0.75,
      "pbrHigh": 1,
      "perLow": 11,
      "perAvg": 16,
      "perHigh": 22,
      "dataConfidence": "確認済み",
      "qualitativeDone": false,
      "held": false,
      "risk": "",
      "catalyst": "含み資産",
      "history": [
        590,
        610,
        600,
        615,
        640,
        630,
        620,
        625,
        605
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/3123"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "3123",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (308円以下)",
        "sellTiming": "目標の90%付近 (922円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "反映済み",
        "financialScreeningCautions": "ネット有利子負債が重い -97.7% / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "3765",
      "name": "ガンホー",
      "sector": "情報通信",
      "price": 2190,
      "shares": 54337100,
      "treasuryShares": 0,
      "cash": 130500,
      "securities": 0,
      "investmentSecurities": 12100,
      "interestDebt": 0,
      "netAssets": 158500,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 2910,
      "eps": 128,
      "pbrLow": 0.75,
      "pbrAvg": 0.95,
      "pbrHigh": 1.25,
      "perLow": 15,
      "perAvg": 19,
      "perHigh": 25,
      "dataConfidence": "確認済み",
      "qualitativeDone": true,
      "held": false,
      "risk": "利益減少傾向",
      "catalyst": "キャッシュリッチ",
      "history": [
        3050,
        2940,
        2810,
        2740,
        2690,
        2660,
        2640,
        2625,
        2190
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/3765"
      },
      "priceAsOf": "2026-06-26",
      "disclosures": [
        {
          "code": "3765",
          "publishedAt": "2026-06-18",
          "title": "業績予想の下方修正に関するお知らせ",
          "url": "https://example.com/3765-risk",
          "catalysts": [
            {
              "type": "リスク",
              "score": -10
            }
          ]
        }
      ],
      "watchlist": null,
      "backtest": {
        "code": "3765",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "買い場待ち",
        "buyTiming": "買いライン到達 (2,100円以下)",
        "sellTiming": "目標の90%付近 (3,292円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "8802",
      "name": "三菱地所",
      "sector": "不動産",
      "price": 4101,
      "shares": 1220000000,
      "treasuryShares": 0,
      "cash": 435000,
      "securities": 0,
      "investmentSecurities": 565000,
      "interestDebt": 3180000,
      "netAssets": 3920000,
      "rentalBook": 4800000,
      "rentalMarket": 9900000,
      "bps": 3210,
      "eps": 230,
      "pbrLow": 0.95,
      "pbrAvg": 1.2,
      "pbrHigh": 1.45,
      "perLow": 15,
      "perAvg": 19,
      "perHigh": 23,
      "dataConfidence": "確認済み",
      "qualitativeDone": true,
      "held": true,
      "risk": "",
      "catalyst": "増配",
      "history": [
        2750,
        2920,
        3100,
        3350,
        3620,
        3810,
        3880,
        3940,
        4101
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/8802"
      },
      "priceAsOf": "2026-06-26",
      "disclosures": [
        {
          "code": "8802",
          "publishedAt": "2026-06-18",
          "title": "配当予想の修正（増配）および累進配当方針に関するお知らせ",
          "url": "https://example.com/8802-dividend",
          "catalysts": [
            {
              "type": "増配",
              "score": 8
            }
          ]
        }
      ],
      "watchlist": null,
      "backtest": {
        "code": "8802",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (3,036円以下)",
        "sellTiming": "目標の90%付近 (4,658円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 1,
        "winRate": 100,
        "averageReturn": 40.4,
        "maxDrawdown": 0,
        "bestScore": 91.5,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "2484",
      "name": "出前館",
      "sector": "サービス",
      "price": 116,
      "shares": 111550000,
      "treasuryShares": 0,
      "cash": 28538,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 0,
      "netAssets": 42000,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 376,
      "eps": -35,
      "pbrLow": 0.35,
      "pbrAvg": 0.6,
      "pbrHigh": 0.9,
      "perLow": 0,
      "perAvg": 0,
      "perHigh": 0,
      "dataConfidence": "確認済み",
      "qualitativeDone": false,
      "held": false,
      "risk": "赤字継続",
      "catalyst": "ネットキャッシュ",
      "history": [
        210,
        190,
        178,
        160,
        148,
        142,
        138,
        135,
        116
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/2484"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "2484",
        "bestStrategyId": "early-value",
        "bestStrategyLabel": "5%以内で早めに買い",
        "timingLabel": "検証弱く見送り",
        "buyTiming": "買いライン+5%以内 (138円以下)",
        "sellTiming": "目標の85%付近 (288円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 1,
        "winRate": 0,
        "averageReturn": -15.9,
        "maxDrawdown": -15.9,
        "bestScore": -28.9,
        "financialScreeningStatus": "反映済み",
        "financialScreeningCautions": "EPSが赤字または未確認 / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "1897",
      "name": "金下建設",
      "sector": "建設",
      "price": 3075,
      "shares": 3800000,
      "treasuryShares": 220000,
      "cash": 16800,
      "securities": 900,
      "investmentSecurities": 6200,
      "interestDebt": 500,
      "netAssets": 31200,
      "rentalBook": 1200,
      "rentalMarket": 3900,
      "bps": 6500,
      "eps": 350,
      "pbrLow": 0.48,
      "pbrAvg": 0.68,
      "pbrHigh": 0.95,
      "perLow": 11,
      "perAvg": 16,
      "perHigh": 22,
      "dataConfidence": "確認済み",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "ネットキャッシュ",
      "history": [
        3600,
        3420,
        3250,
        3100,
        3020,
        2940,
        2890,
        2850,
        3075
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/1897"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": {
        "status": "重点監視",
        "note": "買いラインを下回ったら有報の資産欄を再確認"
      },
      "backtest": {
        "code": "1897",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "検証弱く見送り",
        "buyTiming": "買いライン到達 (3,120円以下)",
        "sellTiming": "目標の90%付近 (6,930円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 1,
        "winRate": 0,
        "averageReturn": -0.8,
        "maxDrawdown": -8.1,
        "bestScore": -4.4,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "9672",
      "name": "東京都競馬",
      "sector": "不動産・レジャー",
      "price": 4875,
      "shares": 28764000,
      "treasuryShares": 900000,
      "cash": 23000,
      "securities": 2100,
      "investmentSecurities": 8600,
      "interestDebt": 17800,
      "netAssets": 113500,
      "rentalBook": 4280,
      "rentalMarket": 212000,
      "bps": 4070,
      "eps": 288,
      "pbrLow": 0.85,
      "pbrAvg": 1.05,
      "pbrHigh": 1.28,
      "perLow": 14,
      "perAvg": 18,
      "perHigh": 20,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": true,
      "risk": "",
      "catalyst": "資産活用",
      "history": [
        3900,
        4200,
        4550,
        4920,
        5250,
        5600,
        5780,
        5850,
        4875
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/9672"
      },
      "priceAsOf": "2026-06-26",
      "disclosures": [
        {
          "code": "9672",
          "publishedAt": "2026-06-18",
          "title": "固定資産の有効活用および長期ビジョンに関するお知らせ",
          "url": "https://example.com/9672-assets",
          "catalysts": [
            {
              "type": "資産活用",
              "score": 6
            }
          ]
        }
      ],
      "watchlist": {
        "status": "保有監視",
        "note": "目標株価到達後の一部利益確定を検討"
      },
      "backtest": {
        "code": "9672",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "財務で見送り",
        "buyTiming": "買いライン到達 (3,417円以下)",
        "sellTiming": "目標の90%付近 (5,040円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "見送り寄り",
        "financialScreeningCautions": "PBR 1.6倍で割安感が薄い / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "8830",
      "name": "住友不動産",
      "sector": "不動産",
      "price": 3572,
      "shares": 475000000,
      "treasuryShares": 0,
      "cash": 250000,
      "securities": 0,
      "investmentSecurities": 120000,
      "interestDebt": 3800000,
      "netAssets": 2100000,
      "rentalBook": 2800000,
      "rentalMarket": 5200000,
      "bps": 4420,
      "eps": 300,
      "pbrLow": 0.9,
      "pbrAvg": 1.2,
      "pbrHigh": 1.55,
      "perLow": 12,
      "perAvg": 18,
      "perHigh": 24,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "賃貸等不動産",
      "history": [
        4100,
        4350,
        4620,
        4980,
        5350,
        5700,
        5980,
        6200,
        3572
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/8830"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "8830",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "財務で見送り",
        "buyTiming": "買いライン到達 (3,600円以下)",
        "sellTiming": "目標の90%付近 (6,480円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "見送り寄り",
        "financialScreeningCautions": "PBR 2.32倍で割安感が薄い / ネット有利子負債が重い -65.34% / 有利子負債が純資産を上回る"
      }
    },
    {
      "code": "8801",
      "name": "三井不動産",
      "sector": "不動産",
      "price": 1480,
      "shares": 2700000000,
      "treasuryShares": 0,
      "cash": 260000,
      "securities": 0,
      "investmentSecurities": 180000,
      "interestDebt": 4200000,
      "netAssets": 3000000,
      "rentalBook": 3500000,
      "rentalMarket": 6400000,
      "bps": 1110,
      "eps": 95,
      "pbrLow": 0.85,
      "pbrAvg": 1.15,
      "pbrHigh": 1.45,
      "perLow": 13,
      "perAvg": 18,
      "perHigh": 23,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "含み資産",
      "history": [
        1080,
        1160,
        1230,
        1340,
        1460,
        1530,
        1590,
        1640,
        1480
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/8801"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "8801",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "財務で見送り",
        "buyTiming": "買いライン到達 (944円以下)",
        "sellTiming": "目標の90%付近 (1,967円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "見送り寄り",
        "financialScreeningCautions": "ネット有利子負債が重い -91.2% / 有利子負債が純資産を上回る / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "9830",
      "name": "トラスコ中山",
      "sector": "卸売",
      "price": 2248,
      "shares": 66000000,
      "treasuryShares": 1200000,
      "cash": 45000,
      "securities": 3000,
      "investmentSecurities": 62000,
      "interestDebt": 20000,
      "netAssets": 180000,
      "rentalBook": 12000,
      "rentalMarket": 35000,
      "bps": 2720,
      "eps": 120,
      "pbrLow": 0.65,
      "pbrAvg": 0.9,
      "pbrHigh": 1.15,
      "perLow": 13,
      "perAvg": 18,
      "perHigh": 24,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "投資有価証券",
      "history": [
        1980,
        2050,
        2140,
        2260,
        2380,
        2420,
        2480,
        2500,
        2248
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/9830"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "9830",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (1,560円以下)",
        "sellTiming": "目標の90%付近 (2,815円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "慎重確認",
        "financialScreeningCautions": "価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "3471",
      "name": "三井不動産ロジスティクスパーク投資法人",
      "sector": "REIT",
      "price": 108600,
      "shares": 1100000,
      "treasuryShares": 0,
      "cash": 18000,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 240000,
      "netAssets": 402000,
      "rentalBook": 520000,
      "rentalMarket": 690000,
      "bps": 365000,
      "eps": 15000,
      "pbrLow": 0.85,
      "pbrAvg": 1.05,
      "pbrHigh": 1.25,
      "perLow": 18,
      "perAvg": 24,
      "perHigh": 30,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "物流不動産",
      "history": [
        395000,
        402000,
        418000,
        430000,
        442000,
        448000,
        452000,
        455000,
        108600
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/3471"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "3471",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "財務で見送り",
        "buyTiming": "買いライン到達 (270,000円以下)",
        "sellTiming": "目標の90%付近 (410,625円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "見送り寄り",
        "financialScreeningCautions": "ネット有利子負債が重い -44.36% / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "8018",
      "name": "三共生興",
      "sector": "卸売",
      "price": 786,
      "shares": 37877715,
      "treasuryShares": 0,
      "cash": 21000,
      "securities": 1200,
      "investmentSecurities": 32000,
      "interestDebt": 4500,
      "netAssets": 61000,
      "rentalBook": 9000,
      "rentalMarket": 24000,
      "bps": 1420,
      "eps": 72,
      "pbrLow": 0.64,
      "pbrAvg": 1.09,
      "pbrHigh": 1.53,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.55倍で割安寄り / PER 15.43倍 / ネットキャッシュあり 15.87%",
      "history": [
        874,
        876,
        845,
        842,
        836,
        800,
        793,
        786
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/8018"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "8018",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (531円以下)",
        "sellTiming": "目標の90%付近 (2,041円目安)",
        "confidence": "参考",
        "sampleCount": 8,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "6513",
      "name": "オリジン",
      "sector": "電機",
      "price": 1075,
      "shares": 6699000,
      "treasuryShares": 300000,
      "cash": 11000,
      "securities": 500,
      "investmentSecurities": 14500,
      "interestDebt": 2200,
      "netAssets": 36000,
      "rentalBook": 3500,
      "rentalMarket": 7600,
      "bps": 5600,
      "eps": 180,
      "pbrLow": 0.35,
      "pbrAvg": 0.55,
      "pbrHigh": 0.8,
      "perLow": 7,
      "perAvg": 11,
      "perHigh": 16,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "ネットキャッシュ",
      "history": [
        980,
        1040,
        1080,
        1130,
        1190,
        1230,
        1260,
        1280,
        1075
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/6513"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "6513",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "財務で見送り",
        "buyTiming": "買いライン到達 (1,260円以下)",
        "sellTiming": "目標の90%付近 (4,032円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 1,
        "winRate": 100,
        "averageReturn": 3.4,
        "maxDrawdown": 0,
        "bestScore": 47,
        "financialScreeningStatus": "見送り寄り",
        "financialScreeningCautions": "PER 67.26倍で高い / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "1443",
      "name": "技研HD",
      "sector": "建設",
      "price": 244,
      "shares": 16000000,
      "treasuryShares": 0,
      "cash": 4800,
      "securities": 200,
      "investmentSecurities": 1800,
      "interestDebt": 1200,
      "netAssets": 10800,
      "rentalBook": 900,
      "rentalMarket": 1800,
      "bps": 675,
      "eps": 34,
      "pbrLow": 0.3,
      "pbrAvg": 0.5,
      "pbrHigh": 0.75,
      "perLow": 6,
      "perAvg": 10,
      "perHigh": 15,
      "dataConfidence": "一部手入力",
      "qualitativeDone": false,
      "held": false,
      "risk": "",
      "catalyst": "ネットキャッシュ",
      "history": [
        185,
        192,
        188,
        198,
        205,
        208,
        212,
        210,
        244
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/1443"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "1443",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (203円以下)",
        "sellTiming": "目標の90%付近 (459円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 1,
        "winRate": 100,
        "averageReturn": 27.1,
        "maxDrawdown": -2.1,
        "bestScore": 73.8,
        "financialScreeningStatus": "慎重確認",
        "financialScreeningCautions": "ネット有利子負債が重い -42.92% / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "9409",
      "name": "テレビ朝日HD",
      "sector": "情報通信",
      "price": 3105,
      "shares": 101060770,
      "treasuryShares": 0,
      "cash": 62000,
      "securities": 8000,
      "investmentSecurities": 210000,
      "interestDebt": 30000,
      "netAssets": 420000,
      "rentalBook": 160000,
      "rentalMarket": 420000,
      "bps": 3920,
      "eps": 160,
      "pbrLow": 0.64,
      "pbrAvg": 1.09,
      "pbrHigh": 1.53,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.53倍で割安寄り / PER 9.85倍で利益面は軽い / ネットキャッシュあり 17.86%",
      "history": [
        3210,
        3220,
        3155,
        3135,
        3080,
        3065,
        3070,
        3105
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/9409"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "9409",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (2,487円以下)",
        "sellTiming": "目標の90%付近 (6,372円目安)",
        "confidence": "参考",
        "sampleCount": 8,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "9402",
      "name": "中部日本放送",
      "sector": "情報通信",
      "price": 1220,
      "shares": 26850877,
      "treasuryShares": 0,
      "cash": 17000,
      "securities": 1000,
      "investmentSecurities": 42000,
      "interestDebt": 2500,
      "netAssets": 76000,
      "rentalBook": 18000,
      "rentalMarket": 52000,
      "bps": 2920,
      "eps": 85,
      "pbrLow": 0.64,
      "pbrAvg": 1.09,
      "pbrHigh": 1.53,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.26倍で割安寄り / PER 13.34倍 / ネットキャッシュが時価総額の73.26%相当",
      "history": [
        686,
        718,
        741,
        757,
        780,
        1220
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/9402"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "9402",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (585円以下)",
        "sellTiming": "目標の90%付近 (4,094円目安)",
        "confidence": "参考",
        "sampleCount": 6,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "9324",
      "name": "安田倉庫",
      "sector": "倉庫",
      "price": 2365,
      "shares": 30200000,
      "treasuryShares": 800000,
      "cash": 18000,
      "securities": 1000,
      "investmentSecurities": 38000,
      "interestDebt": 42000,
      "netAssets": 94000,
      "rentalBook": 72000,
      "rentalMarket": 160000,
      "bps": 3150,
      "eps": 105,
      "pbrLow": 0.38,
      "pbrAvg": 0.58,
      "pbrHigh": 0.82,
      "perLow": 8,
      "perAvg": 12,
      "perHigh": 17,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "倉庫不動産",
      "history": [
        1040,
        1090,
        1160,
        1240,
        1320,
        1390,
        1430,
        1450,
        2365
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/9324"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "9324",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (840円以下)",
        "sellTiming": "目標の90%付近 (2,325円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "慎重確認",
        "financialScreeningCautions": "ネット有利子負債が重い -121.21% / 有利子負債がやや重い / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "8818",
      "name": "京阪神ビルディング",
      "sector": "不動産",
      "price": 1071,
      "shares": 50600000,
      "treasuryShares": 1200000,
      "cash": 24000,
      "securities": 1200,
      "investmentSecurities": 35000,
      "interestDebt": 72000,
      "netAssets": 136000,
      "rentalBook": 120000,
      "rentalMarket": 320000,
      "bps": 2750,
      "eps": 110,
      "pbrLow": 0.45,
      "pbrAvg": 0.68,
      "pbrHigh": 0.95,
      "perLow": 9,
      "perAvg": 13,
      "perHigh": 18,
      "dataConfidence": "一部手入力",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "賃貸等不動産",
      "history": [
        1280,
        1340,
        1420,
        1510,
        1600,
        1680,
        1740,
        1780,
        1071
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/8818"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "8818",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "財務で見送り",
        "buyTiming": "買いライン到達 (990円以下)",
        "sellTiming": "目標の90%付近 (2,351円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "見送り寄り",
        "financialScreeningCautions": "ネット有利子負債が重い -80.66% / 有利子負債が純資産を上回る / 価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "3892",
      "name": "岡山製紙",
      "sector": "紙・パルプ",
      "price": 1620,
      "shares": 4073775,
      "treasuryShares": 0,
      "cash": 7200,
      "securities": 300,
      "investmentSecurities": 2200,
      "interestDebt": 900,
      "netAssets": 16200,
      "rentalBook": 1100,
      "rentalMarket": 2400,
      "bps": 3000,
      "eps": 155,
      "pbrLow": 0.64,
      "pbrAvg": 1.09,
      "pbrHigh": 1.53,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.43倍で割安寄り / PER 9.16倍で利益面は軽い / ネットキャッシュが時価総額の79.44%相当",
      "history": [
        1645,
        1636,
        1638,
        1625,
        1634,
        1631,
        1625,
        1620
      ],
      "edinet": {
        "documentType": "annual",
        "periodEnd": "2026-03-31",
        "submittedAt": "2026-06-19",
        "sourceUrl": "https://example.com/edinet/3892"
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "3892",
        "bestStrategyId": "turnaround",
        "bestStrategyLabel": "下げ止まり反転で買い",
        "timingLabel": "検証弱く見送り",
        "buyTiming": "買いライン+10%以内で反転確認 (1,658円以下)",
        "sellTiming": "目標の90%付近 (4,375円目安)",
        "confidence": "参考",
        "sampleCount": 8,
        "trades": 1,
        "winRate": 0,
        "averageReturn": -1.1,
        "maxDrawdown": -1.1,
        "bestScore": 0.8,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "6276",
      "name": "SiriusVision CO.,LTD.",
      "sector": "Electric Appliances",
      "price": 307,
      "shares": 4008220,
      "treasuryShares": 0,
      "cash": 1086.94,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 270.01,
      "netAssets": 1784.58,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 445.23,
      "eps": 111.58,
      "pbrLow": 0.64,
      "pbrAvg": 1.09,
      "pbrHigh": 1.53,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.67倍で割安寄り / PER 2.69倍で利益面は軽い / ネットキャッシュが時価総額の67.94%相当",
      "history": [
        276,
        276,
        287,
        291,
        294,
        289,
        303,
        300,
        307
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 1086.94,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 270.01,
        "netAssets": 1784.58,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 445.23,
        "eps": 111.58,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "6276",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "買い場待ち",
        "buyTiming": "買いライン到達 (285円以下)",
        "sellTiming": "目標の90%付近 (2,410円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 1,
        "winRate": 100,
        "averageReturn": 11.2,
        "maxDrawdown": 0,
        "bestScore": 56.5,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "7435",
      "name": "NADEX CO.,LTD.",
      "sector": "Wholesale Trade",
      "price": 1292,
      "shares": 8120875,
      "treasuryShares": 0,
      "cash": 4759.89,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 38.32,
      "netAssets": 20596,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 2536.18,
      "eps": 81.12,
      "pbrLow": 0.64,
      "pbrAvg": 1.09,
      "pbrHigh": 1.53,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.49倍で割安寄り / PER 15.29倍 / ネットキャッシュあり 46.89%",
      "history": [
        1093,
        1393,
        1228,
        1288,
        1287,
        1251,
        1288,
        1240,
        1292
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 4759.89,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 38.32,
        "netAssets": 20596,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 2536.18,
        "eps": 81.12,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "7435",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (811円以下)",
        "sellTiming": "目標の90%付近 (3,492円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "7567",
      "name": "SAKAE ELECTRONICS CORPORATION",
      "sector": "Wholesale Trade",
      "price": 523,
      "shares": 5078689,
      "treasuryShares": 0,
      "cash": 1090.79,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 500,
      "netAssets": 4818,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 948.67,
      "eps": 25.6,
      "pbrLow": 0.64,
      "pbrAvg": 1.09,
      "pbrHigh": 1.53,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.58倍で割安寄り / ネットキャッシュあり 21.27% / 有利子負債は軽め",
      "history": [
        531,
        544,
        533,
        546,
        537,
        546,
        548,
        547,
        523
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 1090.79,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 500,
        "netAssets": 4818,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 948.67,
        "eps": 25.6,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "7567",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (256円以下)",
        "sellTiming": "目標の90%付近 (1,306円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "1514",
      "name": "Sumiseki Holdings,Inc.",
      "sector": "Mining",
      "price": 520,
      "shares": 59823096,
      "treasuryShares": 0,
      "cash": 16924,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 0,
      "netAssets": 29150,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 487.27,
      "eps": 26.75,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: ネットキャッシュが時価総額の53.18%相当 / 有利子負債は軽め",
      "history": [
        553,
        551,
        545,
        550,
        537,
        524,
        550,
        532,
        520
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 16924,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 0,
        "netAssets": 29150,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 487.27,
        "eps": 26.75,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "1514",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (268円以下)",
        "sellTiming": "目標の90%付近 (789円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "7885",
      "name": "TAKANO Co.,Ltd.",
      "sector": "Other Products",
      "price": 1057,
      "shares": 15221218,
      "treasuryShares": 0,
      "cash": 8275.25,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 31.52,
      "netAssets": 32511,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 2135.9,
      "eps": 47.96,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.47倍で割安寄り / ネットキャッシュが時価総額の53.46%相当 / 有利子負債は軽め",
      "history": [
        1023,
        1055,
        1044,
        1035,
        1057,
        1058,
        1025,
        1013,
        1057
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 8275.25,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 31.52,
        "netAssets": 32511,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 2135.9,
        "eps": 47.96,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "7885",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (480円以下)",
        "sellTiming": "目標の90%付近 (3,460円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "7901",
      "name": "MATSUMOTO INC.",
      "sector": "Other Products",
      "price": 760,
      "shares": 1131574,
      "treasuryShares": 0,
      "cash": 676.67,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 439.27,
      "netAssets": 996,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 880.19,
      "eps": 136.92,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.87倍で確認余地 / PER 5.62倍で利益面は軽い / ネットキャッシュあり 27.25%",
      "history": [
        776,
        817,
        775,
        789,
        791,
        788,
        782,
        770,
        760
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 676.67,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 439.27,
        "netAssets": 996,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 880.19,
        "eps": 136.92,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "7901",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (660円以下)",
        "sellTiming": "目標の90%付近 (2,957円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "6870",
      "name": "Fenwal Controls of Japan,Ltd.",
      "sector": "Electric Appliances",
      "price": 2540,
      "shares": 5437304,
      "treasuryShares": 0,
      "cash": 4282.9,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 622.94,
      "netAssets": 14607.86,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 2686.6,
      "eps": 156.93,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.93倍で確認余地 / PER 15.89倍 / ネットキャッシュあり 27%",
      "history": [
        2388,
        2398,
        2450,
        2498,
        2466,
        2463,
        2525,
        2493,
        2540
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 4282.9,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 622.94,
        "netAssets": 14607.86,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 2686.6,
        "eps": 156.93,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "6870",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (1,569円以下)",
        "sellTiming": "目標の90%付近 (4,352円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "5939",
      "name": "OTANI KOGYO CO.,LTD.",
      "sector": "Metal Products",
      "price": 4970,
      "shares": 778967,
      "treasuryShares": 0,
      "cash": 1222.59,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 623,
      "netAssets": 4406,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 5656.21,
      "eps": 333.74,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.88倍で確認余地 / PER 14.98倍 / ネットキャッシュあり 15.39%",
      "history": [
        4900,
        5020,
        5000,
        4960,
        4995,
        4975,
        5040,
        5000,
        4970
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 1222.59,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 623,
        "netAssets": 4406,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 5656.21,
        "eps": 333.74,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "5939",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (3,337円以下)",
        "sellTiming": "目標の90%付近 (9,163円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "2303",
      "name": "Dawn Corporation",
      "sector": "Information & Communication",
      "price": 1221,
      "shares": 2587091,
      "treasuryShares": 0,
      "cash": 733.57,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 0,
      "netAssets": 2750.44,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 1063.14,
      "eps": 160.29,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PER 7.72倍で利益面は軽い / ネットキャッシュあり 22.92% / 有利子負債は軽め",
      "history": [
        1225,
        1228,
        1216,
        1223,
        1234,
        1205,
        1254,
        1237,
        1221
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 733.57,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 0,
        "netAssets": 2750.44,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 1063.14,
        "eps": 160.29,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "2303",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (797円以下)",
        "sellTiming": "目標の90%付近 (3,462円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "2332",
      "name": "Quest Co.,Ltd.",
      "sector": "Information & Communication",
      "price": 1744,
      "shares": 5127026,
      "treasuryShares": 0,
      "cash": 3057.48,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 0,
      "netAssets": 7458.49,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 1454.74,
      "eps": 166.96,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PER 10.3倍 / ネットキャッシュあり 34.69% / 有利子負債は軽め",
      "history": [
        1657,
        1709,
        1688,
        1731,
        1751,
        1760,
        1851,
        1719,
        1744
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 3057.48,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 0,
        "netAssets": 7458.49,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 1454.74,
        "eps": 166.96,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "2332",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (1,091円以下)",
        "sellTiming": "目標の90%付近 (3,606円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "3908",
      "name": "コラボス",
      "sector": "情報・通信業",
      "price": 319,
      "shares": 4669262,
      "treasuryShares": 0,
      "cash": 1286.03,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 60,
      "netAssets": 1367.3,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 292.83,
      "eps": 10.74,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: ネットキャッシュが時価総額の82.31%相当 / 有利子負債は軽め",
      "history": [
        305,
        305,
        313,
        320,
        316,
        319,
        319,
        319
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 1286.03,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 60,
        "netAssets": 1367.3,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 292.83,
        "eps": 10.74,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "3908",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (107円以下)",
        "sellTiming": "目標の90%付近 (474円目安)",
        "confidence": "参考",
        "sampleCount": 8,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "6643",
      "name": "戸上電機製作所",
      "sector": "電気機器",
      "price": 5150,
      "shares": 4691273,
      "treasuryShares": 0,
      "cash": 6941.74,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 599.5,
      "netAssets": 24432.57,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 5208.09,
      "eps": 528.41,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.99倍で確認余地 / PER 9.75倍で利益面は軽い / ネットキャッシュあり 26.25%",
      "history": [
        5000,
        5180,
        5190,
        5220,
        5220,
        5120,
        5080,
        5150
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 6941.74,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 599.5,
        "netAssets": 24432.57,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 5208.09,
        "eps": 528.41,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "6643",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (3,906円以下)",
        "sellTiming": "目標の90%付近 (11,414円目安)",
        "confidence": "参考",
        "sampleCount": 8,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "7781",
      "name": "平山ホールディングス",
      "sector": "精密機器",
      "price": 778.5,
      "shares": 6871605,
      "treasuryShares": 0,
      "cash": 6053.26,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 1237,
      "netAssets": 5006.72,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 728.61,
      "eps": 115.22,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PER 6.76倍で利益面は軽い / ネットキャッシュが時価総額の90.03%相当",
      "history": [
        1485,
        780,
        765,
        770,
        768,
        772,
        780,
        779,
        778.5
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 6053.26,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 1237,
        "netAssets": 5006.72,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 728.61,
        "eps": 115.22,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "7781",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (546円以下)",
        "sellTiming": "目標の90%付近 (2,489円目安)",
        "confidence": "参考",
        "sampleCount": 9,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "",
        "financialScreeningCautions": ""
      }
    },
    {
      "code": "1814",
      "name": "大末建設",
      "sector": "建設業",
      "price": 3200,
      "shares": 10295709,
      "treasuryShares": 0,
      "cash": 10776,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 2753,
      "netAssets": 25211,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 2448.69,
      "eps": 374.93,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PER 8.53倍で利益面は軽い / ネットキャッシュあり 24.35% / 有利子負債は軽め",
      "history": [
        3265,
        3275,
        3255,
        3230,
        3140,
        3155,
        3180,
        3200
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 10776,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 2753,
        "netAssets": 25211,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 2448.69,
        "eps": 374.93,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "1814",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (1,837円以下)",
        "sellTiming": "目標の90%付近 (8,098円目安)",
        "confidence": "参考",
        "sampleCount": 8,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "反映済み",
        "financialScreeningCautions": "価格検証は売買回数0回なので参考扱い"
      }
    },
    {
      "code": "4341",
      "name": "西菱電機",
      "sector": "サービス業",
      "price": 871,
      "shares": 3384186,
      "treasuryShares": 0,
      "cash": 1120,
      "securities": 0,
      "investmentSecurities": 0,
      "interestDebt": 900,
      "netAssets": 5528,
      "rentalBook": 0,
      "rentalMarket": 0,
      "bps": 1633.48,
      "eps": 62.06,
      "pbrLow": 0.75,
      "pbrAvg": 1.27,
      "pbrHigh": 1.8,
      "perLow": 10,
      "perAvg": 16,
      "perHigh": 24,
      "dataConfidence": "自動財務確認",
      "qualitativeDone": true,
      "held": false,
      "risk": "",
      "catalyst": "自動財務確認: PBR 0.53倍で割安寄り / PER 14.03倍",
      "history": [
        843,
        833,
        860,
        862,
        864,
        869,
        870,
        871
      ],
      "edinet": {
        "documentType": "auto-financial",
        "periodEnd": "stock-master",
        "submittedAt": "",
        "cash": 1120,
        "securities": 0,
        "investmentSecurities": 0,
        "interestDebt": 900,
        "netAssets": 5528,
        "rentalBook": 0,
        "rentalMarket": 0,
        "bps": 1633.48,
        "eps": 62.06,
        "sourceUrl": ""
      },
      "priceAsOf": "2026-06-26",
      "watchlist": null,
      "backtest": {
        "code": "4341",
        "bestStrategyId": "value-line",
        "bestStrategyLabel": "買いライン到達で買い",
        "timingLabel": "待つ",
        "buyTiming": "買いライン到達 (621円以下)",
        "sellTiming": "目標の90%付近 (2,646円目安)",
        "confidence": "参考",
        "sampleCount": 8,
        "trades": 0,
        "winRate": 0,
        "averageReturn": 0,
        "maxDrawdown": 0,
        "bestScore": -100,
        "financialScreeningStatus": "反映済み",
        "financialScreeningCautions": "価格検証は売買回数0回なので参考扱い"
      }
    }
  ],
  "dataQuality": {
    "ok": true,
    "providerWarnings": [],
    "validationWarnings": [],
    "externalReferenceWarnings": [],
    "missingBacktest": [],
    "missingPrice": [],
    "stalePrice": [],
    "missingEdinet": [],
    "manualInputs": [
      "6505 東洋電機製造",
      "9672 東京都競馬",
      "8830 住友不動産",
      "8801 三井不動産",
      "9830 トラスコ中山",
      "3471 三井不動産ロジスティクスパーク投資法人",
      "6513 オリジン",
      "1443 技研HD",
      "9324 安田倉庫",
      "8818 京阪神ビルディング"
    ],
    "stale": [],
    "nextFixes": [],
    "readiness": {
      "score": 100,
      "label": "本番運用OK",
      "blockers": []
    },
    "coverage": {
      "price": "35/35",
      "freshPrice": "35/35",
      "edinet": "35/35"
    }
  }
};
